title: "Team Blog"
description: "Thoughts, notes, and experiments."
baseurl: "blog" # For user site, leave empty
url: "https://ev1l0rg.github.io/"
 
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
 
author:
  name: "Yo"
  email: "yo@yo.com"
